### ISSUE TITLE
Create Media Queries for screens smaller than 768px

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_01#1]
Create Media Queries for screens smaller than 768px for all elements

**Comment by syed-muheed** [comment]
Can do this too... would be grateful if this is assigned to me

**Comment by premtw** [comment]
Hi @vibeyInfotech  Can you please assign the issue. I'm eager to contribute to it

**Comment by vibey19** [comment]
I have solved this issue...please assign
