### ISSUE TITLE
Create Media Queries for screens between 768px and 991px 

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_01#2]
Create Media Queries for screens between 768px and 991px  For All Elements

**Comment by syed-muheed** [comment]
I can do this... Please assign this issue to me

**Comment by algoplutus1708** [comment]
Please assign this issue to me, I add the media queries !! Thank u!

**Comment by premtw** [comment]
Hi @vibeyInfotech 
Please assign to me. I like to contribute to this as part of the Hcktoberfest
